[build]
  publish = "."

[[redirects]]
  from = "/book"
  to = "/book/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/book/"
  to = "/book/index.html"
  status = 200
  force = false
